# Realistic seed data for major Indian term insurance plans
# Used as fallback when live scraping is blocked/unavailable

SEED_PLANS = [
    {
        "plan_name": "Tech Term Plan",
        "provider": "LIC",
        "source": "seed",
        "sum_assured_min": 50,
        "sum_assured_max": 10000,
        "premium_annual": 8500,
        "policy_term_min": 10,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 98.62,
        "key_features": "Pure term plan|Online purchase|Return of premium option|Accidental death benefit|No medical for low sum assured",
        "source_url": "https://www.licindia.in/Products/Insurance-Plan/lic-tech-term",
    },
    {
        "plan_name": "Click 2 Protect Super",
        "provider": "HDFC Life",
        "source": "seed",
        "sum_assured_min": 50,
        "sum_assured_max": 20000,
        "premium_annual": 9200,
        "policy_term_min": 10,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 99.39,
        "key_features": "Life & CI Rebalance option|Income benefit option|Return of premium|Waiver of premium on disability|Cover till age 85",
        "source_url": "https://www.hdfclife.com/term-insurance-plans/click-2-protect-super",
    },
    {
        "plan_name": "iProtect Smart",
        "provider": "ICICI Prudential",
        "source": "seed",
        "sum_assured_min": 50,
        "sum_assured_max": 20000,
        "premium_annual": 8800,
        "policy_term_min": 5,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 97.90,
        "key_features": "4 plan options|Critical illness cover|Accidental death benefit|Waiver of premium|Terminal illness benefit",
        "source_url": "https://www.iciciprulife.com/term-insurance/iprotect-smart-term-plan.html",
    },
    {
        "plan_name": "eShield Next",
        "provider": "SBI Life",
        "source": "seed",
        "sum_assured_min": 35,
        "sum_assured_max": 20000,
        "premium_annual": 7800,
        "policy_term_min": 5,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 97.05,
        "key_features": "3 plan options|Increasing cover|Level cover|Return of premium|Flexible premium payment",
        "source_url": "https://www.sbilife.co.in/en/individual-life-insurance/term-insurance/eshield-next",
    },
    {
        "plan_name": "Smart Secure Plus",
        "provider": "Max Life",
        "source": "seed",
        "sum_assured_min": 50,
        "sum_assured_max": 100000,
        "premium_annual": 8100,
        "policy_term_min": 10,
        "policy_term_max": 50,
        "age_min": 18,
        "age_max": 60,
        "claim_settlement_ratio": 99.51,
        "key_features": "Highest CSR in private sector|Critical illness rider|In-built terminal illness benefit|Accidental death cover|Joint life cover",
        "source_url": "https://www.maxlifeinsurance.com/term-insurance-plans/smart-secure-plus-plan",
    },
    {
        "plan_name": "Sampoorna Raksha Supreme",
        "provider": "Tata AIA",
        "source": "seed",
        "sum_assured_min": 50,
        "sum_assured_max": 100000,
        "premium_annual": 8300,
        "policy_term_min": 10,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 98.53,
        "key_features": "Comprehensive protection|Whole life cover option|Increasing income option|Disability benefit|Waiver of premium",
        "source_url": "https://www.tataaia.com/all-products/life-insurance/term-insurance/sampoorna-raksha-supreme.html",
    },
    {
        "plan_name": "e-Term Plan",
        "provider": "Kotak Life",
        "source": "seed",
        "sum_assured_min": 25,
        "sum_assured_max": 100000,
        "premium_annual": 7500,
        "policy_term_min": 10,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 98.82,
        "key_features": "Low premiums|3 plan options|Critical illness optional|Accidental death benefit|Online discount",
        "source_url": "https://www.kotaklife.com/online-plans/term-insurance/kotak-e-term",
    },
    {
        "plan_name": "Digi Term Plan",
        "provider": "Bajaj Allianz",
        "source": "seed",
        "sum_assured_min": 25,
        "sum_assured_max": 100000,
        "premium_annual": 7200,
        "policy_term_min": 10,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 98.48,
        "key_features": "Affordable premiums|Flexible sum assured|Critical illness rider|Accidental death benefit|Online process",
        "source_url": "https://www.bajajallianzlife.com/term-insurance/digi-term-plan.html",
    },
    {
        "plan_name": "Saral Jeevan Bima",
        "provider": "Multiple Insurers",
        "source": "seed",
        "sum_assured_min": 5,
        "sum_assured_max": 25,
        "premium_annual": 3500,
        "policy_term_min": 5,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 97.00,
        "key_features": "IRDAI standard plan|Simple eligibility|No exclusions except suicide|Affordable for low income|Easy claim process",
        "source_url": "https://www.irdai.gov.in",
    },
    {
        "plan_name": "Flexi Term Pro",
        "provider": "Canara HSBC",
        "source": "seed",
        "sum_assured_min": 25,
        "sum_assured_max": 100000,
        "premium_annual": 7900,
        "policy_term_min": 5,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 96.38,
        "key_features": "Flexible cover options|Increasing cover|Critical illness add-on|Return of premium option|Joint life cover",
        "source_url": "https://www.canarahsbclife.com/term-insurance/flexi-term-pro",
    },
]
