# Realistic seed data for major Indian term insurance plans
# CSR data sourced from IRDAI Annual Report 2022-23 and coverfox.com
# Used as guaranteed fallback when live scraping is blocked/unavailable

SEED_PLANS = [
    # ── Tier 1: Market Leaders ──────────────────────────────────────────
    {
        "plan_name": "Smart Term Plan Plus",
        "provider": "Axis Max Life",
        "source": "seed",
        "sum_assured_min": 25,
        "sum_assured_max": 100000,
        "premium_annual": 11868,
        "policy_term_min": 10,
        "policy_term_max": 50,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 99.65,
        "key_features": "7 Plan Options|Cover Continuance Benefit|Critical illness rider|Joint life cover|Return of premium option",
        "source_url": "https://www.axismaxlife.com/term-insurance/smart-term-plan-plus",
    },
    {
        "plan_name": "Click 2 Protect Super",
        "provider": "HDFC Life",
        "source": "seed",
        "sum_assured_min": 50,
        "sum_assured_max": 20000,
        "premium_annual": 9200,
        "policy_term_min": 10,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 99.50,
        "key_features": "Life & CI Rebalance option|Income benefit option|Return of premium|Waiver of premium on disability|Cover till age 85",
        "source_url": "https://www.hdfclife.com/term-insurance-plans/click-2-protect-super",
    },
    {
        "plan_name": "Smart Secure Plus",
        "provider": "Max Life",
        "source": "seed",
        "sum_assured_min": 50,
        "sum_assured_max": 100000,
        "premium_annual": 8100,
        "policy_term_min": 10,
        "policy_term_max": 50,
        "age_min": 18,
        "age_max": 60,
        "claim_settlement_ratio": 99.51,
        "key_features": "Highest CSR in private sector|Critical illness rider|Terminal illness benefit|Accidental death cover|Joint life cover",
        "source_url": "https://www.maxlifeinsurance.com/term-insurance-plans/smart-secure-plus-plan",
    },
    {
        "plan_name": "Sampoorna Raksha Promise",
        "provider": "Tata AIA",
        "source": "seed",
        "sum_assured_min": 50,
        "sum_assured_max": 100000,
        "premium_annual": 5796,
        "policy_term_min": 10,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 99.13,
        "key_features": "100% Return of Premiums option|Affordable premiums|Surrender value benefit|Comprehensive protection|Critical illness",
        "source_url": "https://www.tataaia.com/all-products/life-insurance/term-insurance/sampoorna-raksha-promise.html",
    },
    {
        "plan_name": "iProtect Smart Plus",
        "provider": "ICICI Prudential",
        "source": "seed",
        "sum_assured_min": 50,
        "sum_assured_max": 20000,
        "premium_annual": 12996,
        "policy_term_min": 5,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 99.17,
        "key_features": "Life Stage Protection|Smart Exit Benefit|Whole life option|Critical illness|Waiver of premium",
        "source_url": "https://www.iciciprulife.com/term-insurance/iprotect-smart-term-plan.html",
    },
    # ── Tier 2: Established Players ─────────────────────────────────────
    {
        "plan_name": "eTouch Online Term",
        "provider": "Bajaj Allianz",
        "source": "seed",
        "sum_assured_min": 25,
        "sum_assured_max": 100000,
        "premium_annual": 10476,
        "policy_term_min": 10,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 99.23,
        "key_features": "Discount on high sum assured|Flexible payout options|Cover continuance benefit|Critical illness rider|Online process",
        "source_url": "https://www.bajajallianzlife.com/term-insurance/etouch-online-term-plan.html",
    },
    {
        "plan_name": "e-Term Plan",
        "provider": "Kotak Life",
        "source": "seed",
        "sum_assured_min": 25,
        "sum_assured_max": 100000,
        "premium_annual": 7500,
        "policy_term_min": 10,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 98.82,
        "key_features": "Low premiums|3 plan options|Critical illness optional|Accidental death benefit|Online discount",
        "source_url": "https://www.kotaklife.com/online-plans/term-insurance/kotak-e-term",
    },
    {
        "plan_name": "Tech Term Plan",
        "provider": "LIC",
        "source": "seed",
        "sum_assured_min": 50,
        "sum_assured_max": 10000,
        "premium_annual": 8500,
        "policy_term_min": 10,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 98.74,
        "key_features": "Pure term plan|Government-backed|Online purchase|Return of premium option|Accidental death benefit",
        "source_url": "https://www.licindia.in/Products/Insurance-Plan/lic-tech-term",
    },
    {
        "plan_name": "Digi-Term Plan",
        "provider": "Reliance Nippon Life",
        "source": "seed",
        "sum_assured_min": 25,
        "sum_assured_max": 100000,
        "premium_annual": 7600,
        "policy_term_min": 10,
        "policy_term_max": 35,
        "age_min": 18,
        "age_max": 60,
        "claim_settlement_ratio": 98.67,
        "key_features": "Affordable premiums|Flexible sum assured|Critical illness rider|Accidental death benefit|Online process",
        "source_url": "https://www.reliancenipponlife.com/term-insurance/digi-term",
    },
    {
        "plan_name": "Click 2 Protect Life",
        "provider": "HDFC Life",
        "source": "seed",
        "sum_assured_min": 50,
        "sum_assured_max": 20000,
        "premium_annual": 8800,
        "policy_term_min": 10,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 98.66,
        "key_features": "3D Life cover|Critical illness|Return of premium|Waiver of premium|Affordable premiums",
        "source_url": "https://www.hdfclife.com/term-insurance-plans/click-2-protect-life",
    },
    {
        "plan_name": "Total Protect Plus",
        "provider": "Edelweiss Life",
        "source": "seed",
        "sum_assured_min": 25,
        "sum_assured_max": 100000,
        "premium_annual": 7700,
        "policy_term_min": 10,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 98.09,
        "key_features": "Total Protect Plus|Critical illness|Accidental death|Income benefit|Waiver of premium",
        "source_url": "https://www.edelweisslife.in/term-insurance/total-protect-plus",
    },
    {
        "plan_name": "DigiShield Plan",
        "provider": "Aditya Birla Sun Life",
        "source": "seed",
        "sum_assured_min": 30,
        "sum_assured_max": 100000,
        "premium_annual": 8600,
        "policy_term_min": 10,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 98.07,
        "key_features": "Comprehensive protection|Critical illness|Accidental death benefit|Income benefit|Waiver of premium",
        "source_url": "https://lifeinsurance.adityabirlacapital.com/term-insurance/shield-plan",
    },
    {
        "plan_name": "eShield Next",
        "provider": "SBI Life",
        "source": "seed",
        "sum_assured_min": 35,
        "sum_assured_max": 20000,
        "premium_annual": 7800,
        "policy_term_min": 5,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 97.05,
        "key_features": "3 plan options|Increasing cover|Level cover|Return of premium|Flexible premium payment",
        "source_url": "https://www.sbilife.co.in/en/individual-life-insurance/term-insurance/eshield-next",
    },
    # ── Tier 3: Mid-sized Insurers ──────────────────────────────────────
    {
        "plan_name": "iSelect Smart360",
        "provider": "Canara HSBC Life",
        "source": "seed",
        "sum_assured_min": 25,
        "sum_assured_max": 100000,
        "premium_annual": 7900,
        "policy_term_min": 5,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 98.44,
        "key_features": "Flexible cover options|Increasing cover|Critical illness add-on|Return of premium|Joint life cover",
        "source_url": "https://www.canarahsbclife.com/term-insurance",
    },
    {
        "plan_name": "i-Term Smart",
        "provider": "Aviva India",
        "source": "seed",
        "sum_assured_min": 25,
        "sum_assured_max": 100000,
        "premium_annual": 8000,
        "policy_term_min": 10,
        "policy_term_max": 35,
        "age_min": 18,
        "age_max": 60,
        "claim_settlement_ratio": 98.39,
        "key_features": "Multiple options|Critical illness|Accidental death|Return of premium|Flexible payment",
        "source_url": "https://www.avivaindiablog.com/life-insurance/term-insurance",
    },
    {
        "plan_name": "iTerm Prime Plan",
        "provider": "Aegon Life",
        "source": "seed",
        "sum_assured_min": 25,
        "sum_assured_max": 100000,
        "premium_annual": 7600,
        "policy_term_min": 5,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 99.03,
        "key_features": "Affordable premiums|Return of premium option|Critical illness|Accidental death benefit|Income benefit",
        "source_url": "https://www.aegonlife.com/insurance-products/iTerm-Prime",
    },
    {
        "plan_name": "Smart Jeevan",
        "provider": "Bharti AXA Life",
        "source": "seed",
        "sum_assured_min": 25,
        "sum_assured_max": 100000,
        "premium_annual": 8200,
        "policy_term_min": 10,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 99.09,
        "key_features": "Comprehensive cover|Critical illness|Accidental death benefit|Income benefit|Waiver of premium",
        "source_url": "https://www.bharti-axalife.com/products/protection/smart-jeevan-plan",
    },
    {
        "plan_name": "Mera Term Plan Plus",
        "provider": "PNB MetLife",
        "source": "seed",
        "sum_assured_min": 25,
        "sum_assured_max": 100000,
        "premium_annual": 8400,
        "policy_term_min": 10,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 97.33,
        "key_features": "Flexible cover options|Critical illness|Accidental death|Return of premium|Family income benefit",
        "source_url": "https://www.pnbmetlife.com/products/protection/mera-term-plan-plus.html",
    },
    {
        "plan_name": "Smart Life Plan",
        "provider": "Future Generali",
        "source": "seed",
        "sum_assured_min": 25,
        "sum_assured_max": 100000,
        "premium_annual": 7400,
        "policy_term_min": 10,
        "policy_term_max": 35,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 96.15,
        "key_features": "Affordable premiums|Flexible payout|Critical illness|Accidental death benefit|Online process",
        "source_url": "https://www.futuregenerali.in/life-insurance/term-insurance",
    },
    {
        "plan_name": "e-Term Plan",
        "provider": "IndiaFirst Life",
        "source": "seed",
        "sum_assured_min": 50,
        "sum_assured_max": 100000,
        "premium_annual": 7500,
        "policy_term_min": 5,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 96.92,
        "key_features": "Affordable term plan|Critical illness|Accidental death|Flexible payout options|Online process",
        "source_url": "https://www.indiafirstlife.com/term-insurance",
    },
    # ── Entry-level / Inclusive Plans ──────────────────────────────────
    {
        "plan_name": "Saral Jeevan Bima",
        "provider": "Multiple Insurers (IRDAI Mandated)",
        "source": "seed",
        "sum_assured_min": 5,
        "sum_assured_max": 25,
        "premium_annual": 3500,
        "policy_term_min": 5,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 97.00,
        "key_features": "IRDAI standardized plan|Simple eligibility|No exclusions except suicide|Affordable for low income|Easy claim process",
        "source_url": "https://www.irdai.gov.in",
    },
    {
        "plan_name": "Sampoorna Raksha Supreme",
        "provider": "Tata AIA",
        "source": "seed",
        "sum_assured_min": 50,
        "sum_assured_max": 100000,
        "premium_annual": 8300,
        "policy_term_min": 10,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 98.53,
        "key_features": "Comprehensive protection|Whole life cover option|Increasing income option|Disability benefit|Waiver of premium",
        "source_url": "https://www.tataaia.com/all-products/life-insurance/term-insurance/sampoorna-raksha-supreme.html",
    },
    {
        "plan_name": "iProtect Smart",
        "provider": "ICICI Prudential",
        "source": "seed",
        "sum_assured_min": 50,
        "sum_assured_max": 20000,
        "premium_annual": 8800,
        "policy_term_min": 5,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 97.82,
        "key_features": "4 plan options|Critical illness cover|Accidental death benefit|Waiver of premium|Terminal illness benefit",
        "source_url": "https://www.iciciprulife.com/term-insurance/iprotect-smart-term-plan.html",
    },
    # ── Additional Insurers ─────────────────────────────────────────────
    {
        "plan_name": "Mera Term Plan",
        "provider": "Bandhan Life",
        "source": "seed",
        "sum_assured_min": 25,
        "sum_assured_max": 100000,
        "premium_annual": 7800,
        "policy_term_min": 10,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 98.61,
        "key_features": "Flexible cover options|Critical illness|Accidental death|Return of premium|Easy online process",
        "source_url": "https://www.bandhanlife.com/term-insurance",
    },
    {
        "plan_name": "Smart Term Plan",
        "provider": "Exide Life",
        "source": "seed",
        "sum_assured_min": 25,
        "sum_assured_max": 100000,
        "premium_annual": 8000,
        "policy_term_min": 10,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 98.54,
        "key_features": "Affordable premiums|Flexible payout|Critical illness|Accidental death|Online process",
        "source_url": "https://www.hdfclife.com/term-insurance-plans",
    },
    {
        "plan_name": "Saral Jeevan Bima",
        "provider": "Kotak Life",
        "source": "seed",
        "sum_assured_min": 5,
        "sum_assured_max": 25,
        "premium_annual": 3200,
        "policy_term_min": 5,
        "policy_term_max": 40,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 98.82,
        "key_features": "IRDAI standardized plan|Simple eligibility|No exclusions except suicide|Affordable|Easy claim process",
        "source_url": "https://www.kotaklife.com/online-plans/term-insurance",
    },
    {
        "plan_name": "Axis Max Life Smart Secure Plus Plan",
        "provider": "Axis Max Life",
        "source": "seed",
        "sum_assured_min": 25,
        "sum_assured_max": 100000,
        "premium_annual": 11844,
        "policy_term_min": 10,
        "policy_term_max": 50,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 99.65,
        "key_features": "Self-employed friendly|Joint life cover option|Critical illness rider|Terminal illness benefit|Multiple payout options",
        "source_url": "https://www.maxlifeinsurance.com/term-insurance-plans/smart-secure-plus-plan",
    },
    {
        "plan_name": "Star Union Dai-ichi Premier Protection Plan",
        "provider": "Star Union Dai-ichi Life",
        "source": "seed",
        "sum_assured_min": 25,
        "sum_assured_max": 50000,
        "premium_annual": 7200,
        "policy_term_min": 10,
        "policy_term_max": 30,
        "age_min": 18,
        "age_max": 65,
        "claim_settlement_ratio": 96.81,
        "key_features": "Affordable premiums|Simple process|Death benefit|Flexible premium payment|Online purchase",
        "source_url": "https://www.starunionlife.com/term-insurance",
    },
]

